### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by gauthiergalon** [LuyNagda/transcendence#35]

**Comment by gauthiergalon** [comment]
Need one edit one the change password form to change the class to form-control

**Comment by LuyNagda** [comment]
should I add it in all the fields, in all the forms?

**Comment by gauthiergalon** [comment]
i already add it in the other forms its just only in the change password form i didnt find where to edit the class

**Comment by LuyNagda** [comment]
[https://github.com/LuyNagda/transcendence/compare/main...luyforlyon/42-37-change-password](https://github.com/LuyNagda/transcendence/compare/main...luyforlyon/42-37-change-password) - Finished completing that in this commit, you can merge and let me know if this is good
